cmake_policy(SET CMP0048 NEW)
cmake_minimum_required(VERSION 3.20)
set(LIB_DAISY daisy)

set(LIB_DAISY_PATH /home/me/Workspace/other/libDaisy)
set(MODULE_DIR "${LIB_DAISY_PATH}/src")


add_library(${LIB_DAISY} STATIC
        ${MODULE_DIR}/sys/dma.c
        ${MODULE_DIR}/hid/audio.cpp
        ${MODULE_DIR}/sys/fatfs.cpp
        ${MODULE_DIR}/per/gpio.cpp
        ${MODULE_DIR}/per/rng.cpp
        ${MODULE_DIR}/per/sai.cpp
        ${MODULE_DIR}/per/sdmmc.cpp
        ${MODULE_DIR}/util/bsp_sd_diskio.c
        ${MODULE_DIR}/util/hal_map.c
        ${MODULE_DIR}/util/oled_fonts.c
        ${MODULE_DIR}/util/sd_diskio.c
        ${MODULE_DIR}/util/usbh_diskio.c
        ${MODULE_DIR}/util/unique_id.c
        ${MODULE_DIR}/sys/system_stm32h7xx.c
        ${MODULE_DIR}/usbd/usbd_cdc_if.c
        ${MODULE_DIR}/usbd/usbd_desc.c
        ${MODULE_DIR}/usbd/usbd_conf.c
        ${MODULE_DIR}/usbh/usbh_conf.c
        ${MODULE_DIR}/daisy_seed.cpp
        ${MODULE_DIR}/daisy_pod.cpp
        ${MODULE_DIR}/daisy_patch.cpp
        ${MODULE_DIR}/daisy_petal.cpp
        ${MODULE_DIR}/daisy_field.cpp
        ${MODULE_DIR}/daisy_versio.cpp
        ${MODULE_DIR}/daisy_legio.cpp
        ${MODULE_DIR}/daisy_patch_sm.cpp
        ${MODULE_DIR}/sys/system.cpp
        ${MODULE_DIR}/dev/sr_595.cpp
        ${MODULE_DIR}/dev/codec_ak4556.cpp
        ${MODULE_DIR}/dev/codec_pcm3060.cpp
        ${MODULE_DIR}/dev/codec_wm8731.cpp
        ${MODULE_DIR}/dev/lcd_hd44780.cpp
        ${MODULE_DIR}/hid/ctrl.cpp
        ${MODULE_DIR}/hid/encoder.cpp
        ${MODULE_DIR}/hid/gatein.cpp
        ${MODULE_DIR}/hid/led.cpp
        ${MODULE_DIR}/hid/midi.cpp
        ${MODULE_DIR}/hid/midi_parser.cpp
        ${MODULE_DIR}/hid/parameter.cpp
        ${MODULE_DIR}/hid/rgb_led.cpp
        ${MODULE_DIR}/hid/switch.cpp
        ${MODULE_DIR}/hid/usb.cpp
        ${MODULE_DIR}/hid/usb_host.cpp
        ${MODULE_DIR}/hid/usb_midi.cpp
        ${MODULE_DIR}/hid/wavplayer.cpp
        ${MODULE_DIR}/hid/logger.cpp
        ${MODULE_DIR}/per/adc.cpp
        ${MODULE_DIR}/per/dac.cpp
        ${MODULE_DIR}/per/i2c.cpp
        ${MODULE_DIR}/per/qspi.cpp
        ${MODULE_DIR}/dev/sdram.cpp
        ${MODULE_DIR}/per/spi.cpp
        ${MODULE_DIR}/per/spiMultislave.cpp
        ${MODULE_DIR}/per/tim.cpp
        ${MODULE_DIR}/per/uart.cpp
        ${MODULE_DIR}/ui/AbstractMenu.cpp
        ${MODULE_DIR}/ui/FullScreenItemMenu.cpp
        ${MODULE_DIR}/ui/UI.cpp
        ${MODULE_DIR}/util/color.cpp
        ${MODULE_DIR}/util/WaveTableLoader.cpp
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_msp_template.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_alarm_template.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_wakeup_template.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_tim_template.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_adc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_bdma.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_comp.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_crc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dac.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_delayblock.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma2d.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_exti.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_gpio.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_hrtim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_i2c.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lptim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lpuart.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_mdma.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_opamp.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_pwr.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rcc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rng.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rtc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_spi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_swpmi.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_tim.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usart.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_utils.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_scsi.c
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c
        ${MODULE_DIR}/../Middlewares/Third_Party/FatFs/src/diskio.c
        ${MODULE_DIR}/../Middlewares/Third_Party/FatFs/src/ff.c
        ${MODULE_DIR}/../Middlewares/Third_Party/FatFs/src/ff_gen_drv.c
        ${MODULE_DIR}/../core/startup_stm32h750xx.c
)

target_include_directories(${LIB_DAISY} PUBLIC
        ${MODULE_DIR}
        ${MODULE_DIR}/../Drivers/CMSIS/Include
        ${MODULE_DIR}/../Drivers/CMSIS/Device/ST/STM32H7xx/Include
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc
        ${MODULE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Core/Inc
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Inc
        ${MODULE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc
        ${MODULE_DIR}/../Middlewares/Third_Party/FatFs/src
        ${MODULE_DIR}/sys
        ${MODULE_DIR}/usbd
        ${MODULE_DIR}/usbh
)
set_target_properties(${LIB_DAISY} PROPERTIES
        CXX_STANDARD 14
        CXX_STANDARD_REQUIRED
        C_STANDARD 11
        C_STANDARD_REQUIRED
)